fun main(){
    print("student Enrollment No.: ")
    var stEno = readLine()
    print("student Name: ")
    var stName = readLine()
    print("student Branch: ")
    var stBranch = readLine()
    print("student Class: ")
    var stClass = readLine()
    print("student Batch: ")
    var stBatch = readLine()
    print("student College Name: ")
    var stClg = readLine()
    print("student University Name: ")
    var stUni = readLine()
    print("student Age: ")
    var stAge = readLine()!!.toInt()
    println("\n\n********************\n\n")
    println("Student's Data:")
    println("Enrollment No.: $stEno")
    println("Name: $stName")
    println("Age: $stAge")
    println("Branch: $stBranch")
    println("Class: $stClass")
    println("Batch: $stBatch")
    println("College Name: $stClg")
    println("University Name: $stUni")
}